### ISSUE TITLE
CO2 Sensor crashes

### ISSUE THREAD

**Issue by schwabe** [florianL21/zigbee-co2-sensor#6]
Hey, first of all, this seem to be a nice project. I am trying to get it running but both the precompiled binary as well as my self-built version seem to crash immeadiately after the single shot measurement of the SDC sensor. I attached the log output from my self compiled version below.  Any what might cause this or how I can debug this? 

```
ELF file SHA256: a049482e0

Rebooting...
ESP-ROM:esp32c6-20220919
Build:Sep 19 2022
rst:0xc (SW_CPU),boot:0x7b (SPI_FAST_FLASH_BOOT)
Saved PC:0x4001975a
--- 0x4001975a: software_reset_cpu in ROM

SPIWP:0xee
mode:DIO, clock div:2
load:0x40875720,len:0x18ec
load:0x4086c110,len:0xe5c
load:0x4086e610,len:0x2f50
entry 0x4086c11a
I (22) boot: ESP-IDF v5.3.2-dirty 2nd stage bootloader
I (23) boot: compile time Jan  4 2025 00:49:24
I (24) boot: chip revision: v0.1
I (25) boot: efuse block revision: v0.3
I (30) boot.esp32c6: SPI Speed      : 80MHz
I (35) boot.esp32c6: SPI Mode       : DIO
I (39) boot.esp32c6: SPI Flash Size : 2MB
I (44) boot: Enabling RNG early entropy source...
I (50) boot: Partition Table:
I (53) boot: ## Label            Usage          Type ST Offset   Length
I (60) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (68) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (75) boot:  2 factory          factory app      00 00 00010000 000fa000
I (83) boot:  3 zb_storage       Unknown data     01 81 0010a000 00004000
I (90) boot:  4 zb_fct           Unknown data     01 81 0010e000 00000400
I (98) boot: End of partition table
I (102) esp_image: segment 0: paddr=00010020 vaddr=42060020 size=1293ch ( 76092) map
I (139) esp_image: segment 1: paddr=00022964 vaddr=40800000 size=056b4h ( 22196) load
I (150) esp_image: segment 2: paddr=00028020 vaddr=42000020 size=5b53ch (374076) map
I (290) esp_image: segment 3: paddr=00083564 vaddr=408056b4 size=0c3e0h ( 50144) load
I (312) esp_image: segment 4: paddr=0008f94c vaddr=40811aa0 size=021c0h (  8640) load
I (318) esp_image: segment 5: paddr=00091b14 vaddr=50000000 size=00050h (    80) load
I (320) esp_image: segment 6: paddr=00091b6c vaddr=50000050 size=0000ch (    12) load
I (335) boot: Loaded app from partition at offset 0x10000
I (336) boot: Disabling RNG early entropy source...
I (351) cpu_start: Unicore app
I (360) cpu_start: Pro cpu start user code
I (360) cpu_start: cpu freq: 160000000 Hz
I (360) app_init: Application information:
I (363) app_init: Project name:     zigbee_co2_sensor
I (368) app_init: App version:      1.0.0-10-g55ff1ba
I (374) app_init: Compile time:     Jan  4 2025 00:49:19
I (380) app_init: ELF file SHA256:  a049482e0...
I (385) app_init: ESP-IDF:          v5.3.2-dirty
I (391) efuse_init: Min chip rev:     v0.0
I (395) efuse_init: Max chip rev:     v0.99 
I (400) efuse_init: Chip rev:         v0.1
I (405) heap_init: Initializing. RAM available for dynamic allocation:
I (412) heap_init: At 408183B0 len 00064260 (400 KiB): RAM
I (418) heap_init: At 4087C610 len 00002F54 (11 KiB): RAM
I (425) heap_init: At 5000005C len 00003F8C (15 KiB): RTCRAM
I (432) spi_flash: detected chip: generic
I (436) spi_flash: flash io: dio
W (440) spi_flash: Detected size(4096k) larger than the size in the binary image header(2048k). Using the size in the binary image header.
I (453) sleep: Enable automatic switching of GPIO sleep configuration
I (460) sleep_clock: System Power, Clock and Reset sleep retention initialization
I (479) pm: Frequency switching config: CPU_MAX: 160, APB_MAX: 80, APB_MIN: 40, Light sleep: DISABLED
I (480) coexist: coex firmware version: cbb41d7
I (483) coexist: coexist rom version 5b8dcfa
I (489) main_task: Started on CPU0
I (492) main_task: Calling app_main()
I (496) gpio: GPIO[3]| InputEn: 0| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 
I (506) gpio: GPIO[14]| InputEn: 0| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 
I (618) pm: Frequency switching config: CPU_MAX: 160, APB_MAX: 80, APB_MIN: 40, Light sleep: ENABLED
I (619) esp_zb_sleep: Enable ieee802154 zigbee light sleep, the wake up source is ESP timer
I (627) phy_init: phy_version 320,348a293,Sep  3 2024,16:33:12
I (673) phy: libbtbb version: 04952fd, Sep  3 2024, 16:33:30
I (674) sleep_clock: Modem Power, Clock and Reset sleep retention initialization
I (694) main_task: Returned from app_main()
I (695) CO2: ZDO signal: ZDO Config Ready (0x17), status: ESP_FAIL
I (696) CO2: Zigbee stack initialized
W (3027) CO2: Failed to initialize Zigbee stack (status: ESP_FAIL). Resetting the esp after 2s
ESP-ROM:esp32c6-20220919
Build:Sep 19 2022
rst:0xc (SW_CPU),boot:0x7b (SPI_FAST_FLASH_BOOT)
Saved PC:0x4001975a
--- 0x4001975a: software_reset_cpu in ROM

SPIWP:0xee
mode:DIO, clock div:2
load:0x40875720,len:0x18ec
load:0x4086c110,len:0xe5c
load:0x4086e610,len:0x2f50
entry 0x4086c11a
I (22) boot: ESP-IDF v5.3.2-dirty 2nd stage bootloader
I (23) boot: compile time Jan  4 2025 00:49:24
I (24) boot: chip revision: v0.1
I (25) boot: efuse block revision: v0.3
I (30) boot.esp32c6: SPI Speed      : 80MHz
I (35) boot.esp32c6: SPI Mode       : DIO
I (39) boot.esp32c6: SPI Flash Size : 2MB
I (44) boot: Enabling RNG early entropy source...
I (50) boot: Partition Table:
I (53) boot: ## Label            Usage          Type ST Offset   Length
I (60) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (68) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (75) boot:  2 factory          factory app      00 00 00010000 000fa000
I (83) boot:  3 zb_storage       Unknown data     01 81 0010a000 00004000
I (90) boot:  4 zb_fct           Unknown data     01 81 0010e000 00000400
I (98) boot: End of partition table
I (102) esp_image: segment 0: paddr=00010020 vaddr=42060020 size=1293ch ( 76092) map
I (139) esp_image: segment 1: paddr=00022964 vaddr=40800000 size=056b4h ( 22196) load
I (150) esp_image: segment 2: paddr=00028020 vaddr=42000020 size=5b53ch (374076) map
I (290) esp_image: segment 3: paddr=00083564 vaddr=408056b4 size=0c3e0h ( 50144) load
I (312) esp_image: segment 4: paddr=0008f94c vaddr=40811aa0 size=021c0h (  8640) load
I (318) esp_image: segment 5: paddr=00091b14 vaddr=50000000 size=00050h (    80) load
I (320) esp_image: segment 6: paddr=00091b6c vaddr=50000050 size=0000ch (    12) load
I (335) boot: Loaded app from partition at offset 0x10000
I (336) boot: Disabling RNG early entropy source...
I (351) cpu_start: Unicore app
I (360) cpu_start: Pro cpu start user code
I (360) cpu_start: cpu freq: 160000000 Hz
I (360) app_init: Application information:
I (363) app_init: Project name:     zigbee_co2_sensor
I (368) app_init: App version:      1.0.0-10-g55ff1ba
I (374) app_init: Compile time:     Jan  4 2025 00:49:19
I (380) app_init: ELF file SHA256:  a049482e0...
I (385) app_init: ESP-IDF:          v5.3.2-dirty
I (391) efuse_init: Min chip rev:     v0.0
I (395) efuse_init: Max chip rev:     v0.99 
I (400) efuse_init: Chip rev:         v0.1
I (405) heap_init: Initializing. RAM available for dynamic allocation:
I (412) heap_init: At 408183B0 len 00064260 (400 KiB): RAM
I (418) heap_init: At 4087C610 len 00002F54 (11 KiB): RAM
I (425) heap_init: At 5000005C len 00003F8C (15 KiB): RTCRAM
I (432) spi_flash: detected chip: generic
I (436) spi_flash: flash io: dio
W (439) spi_flash: Detected size(4096k) larger than the size in the binary image header(2048k). Using the size in the binary image header.
I (453) sleep: Enable automatic switching of GPIO sleep configuration
I (460) sleep_clock: System Power, Clock and Reset sleep retention initialization
I (479) pm: Frequency switching config: CPU_MAX: 160, APB_MAX: 80, APB_MIN: 40, Light sleep: DISABLED
I (480) coexist: coex firmware version: cbb41d7
I (483) coexist: coexist rom version 5b8dcfa
I (489) main_task: Started on CPU0
I (492) main_task: Calling app_main()
I (496) gpio: GPIO[3]| InputEn: 0| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 
I (506) gpio: GPIO[14]| InputEn: 0| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:0 
I (618) pm: Frequency switching config: CPU_MAX: 160, APB_MAX: 80, APB_MIN: 40, Light sleep: ENABLED
I (619) esp_zb_sleep: Enable ieee802154 zigbee light sleep, the wake up source is ESP timer
I (627) phy_init: phy_version 320,348a293,Sep  3 2024,16:33:12
I (674) phy: libbtbb version: 04952fd, Sep  3 2024, 16:33:30
I (675) sleep_clock: Modem Power, Clock and Reset sleep retention initialization
I (695) main_task: Returned from app_main()
I (696) CO2: ZDO signal: ZDO Config Ready (0x17), status: ESP_FAIL
I (697) CO2: Zigbee stack initialized
I (3647) CO2: Device started up in non factory-reset mode
I (3648) CO2: Device rebooted
I (3649) gpio: GPIO[22]| InputEn: 1| OutputEn: 1| OpenDrain: 1| Pullup: 1| Pulldown: 0| Intr:0 
I (3656) gpio: GPIO[23]| InputEn: 1| OutputEn: 1| OpenDrain: 1| Pullup: 1| Pulldown: 0| Intr:0 
I (3665) sdc41_task: First boot after power cycle. Resetting SCD4x sensor state, some i2c errors are expected
I (4218) sdc41_task: serial: 0x5341bb073b5e
I (4218) sdc41_task: Triggering SCD4x single shot measurement...
I (9223) sdc41_task: Hum: 60.8 %; Tmp: 16.6 °C; CO2: 2255 ppm

assert failed: vPortExitCritical port.c:632 (port_uxCriticalNesting[0] > 0)
Core  0 register dump:
MEPC    : 0x408008aa  RA      : 0x4080afaa  SP      : 0x4081ef50  GP      : 0x408122a4  
--- 0x408008aa: panic_abort at /Users/arne/oss/esp/v5.3.2/esp-idf/components/esp_system/panic.c:463
0x4080afaa: __ubsan_include at /Users/arne/oss/esp/v5.3.2/esp-idf/components/esp_system/ubsan.c:311

TP      : 0x4081f240  T0      : 0x37363534  T1      : 0x7271706f  T2      : 0x33323130  
S0/FP   : 0x0000007c  S1      : 0x00000001  A0      : 0x4081ef8c  A1      : 0x40812db9  
A2      : 0x00000001  A3      : 0x00000029  A4      : 0x00000001  A5      : 0x40818000  
A6      : 0x00000000  A7      : 0x76757473  S2      : 0x00000009  S3      : 0x4081f0ab  
S4      : 0x40812db8  S5      : 0x0006f578  S6      : 0x00000000  S7      : 0x008627a0  
S8      : 0x00000000  S9      : 0x00000000  S10     : 0x00000000  S11     : 0x00000007  
T3      : 0x6e6d6c6b  T4      : 0x6a696867  T5      : 0x66656463  T6      : 0x62613938  
MSTATUS : 0x00001881  MTVEC   : 0x40800001  MCAUSE  : 0x00000007  MTVAL   : 0x00000000  
--- 0x40800001: _vector_table at /Users/arne/oss/esp/v5.3.2/esp-idf/components/riscv/vectors_intc.S:54

MHARTID : 0x00000000  

Stack memory:
4081ef50: 0x600aa000 0x00000000 0x4206eeb0 0x408109de 0x40812d9c 0x4206eeb0 0x40812dac 0x42062db5
--- 0x408109de: newlib_include_assert_impl at /Users/arne/oss/esp/v5.3.2/esp-idf/components/newlib/assert.c:92

4081ef70: 0x40812db0 0x4081ef84 0x40812db4 0x42062dbc 0x40812db8 0x00323336 0x408242d8 0x65737361
4081ef90: 0x66207472 0x656c6961 0x76203a64 0x74726f50 0x74697845 0x74697243 0x6c616369 0x726f7020
4081efb0: 0x3a632e74 0x20323336 0x726f7028 0x78755f74 0x74697243 0x6c616369 0x7473654e 0x5b676e69
4081efd0: 0x3e205d30 0x00293020 0x408242d8 0x4080b66c 0x00000020 0x4081f250 0x40824330 0x00000000
--- 0x4080b66c: xQueueGenericSend at /Users/arne/oss/esp/v5.3.2/esp-idf/components/freertos/FreeRTOS-Kernel/queue.c:1057

4081eff0: 0x40824288 0x00000004 0x408242a8 0x40802b66 0x00000000 0xffffffff 0x408242d8 0x4081f0a8
--- 0x40802b66: lock_release_generic at /Users/arne/oss/esp/v5.3.2/esp-idf/components/newlib/locks.c:197

4081f010: 0x00000000 0x4081f250 0x408242d8 0x4080b82e 0x40880000 0x00000004 0x40824288 0x40802b66
--- 0x4080b82e: xQueueGiveMutexRecursive at /Users/arne/oss/esp/v5.3.2/esp-idf/components/freertos/FreeRTOS-Kernel/queue.c:796
0x40802b66: lock_release_generic at /Users/arne/oss/esp/v5.3.2/esp-idf/components/newlib/locks.c:197

4081f030: 0x4082538c 0x40825728 0x7fffffff 0x4081f0a8 0x00000000 0x00000000 0x00000008 0x40802c2c
--- 0x40802c2c: _lock_release_recursive at /Users/arne/oss/esp/v5.3.2/esp-idf/components/newlib/locks.c:212

4081f050: 0x4082538c 0x00000000 0x00000000 0x42000000 0x0000000f 0x4081f0c0 0x7fffffff 0x000000ff
4081f070: 0x40816a40 0x00000000 0x40816a60 0x4080c264 0x00000000 0x4081f0d8 0x00000008 0x42042336
--- 0x4080c264: vPortExitCritical at /Users/arne/oss/esp/v5.3.2/esp-idf/components/freertos/FreeRTOS-Kernel/portable/riscv/port.c:638
0x42042336: zb_osif_enable_all_interrupts at ??:?

4081f090: 0x0000000f 0x00000000 0x00000001 0x42021824 0x0000000f 0x4081f0c0 0x00000012 0x00000000
--- 0x42021824: zb_mac_logic_iteration at ??:?

4081f0b0: 0x0000000f 0x00000000 0x00000001 0x4204216e 0x00000200 0x00000000 0x00000000 0x00000000
--- 0x4204216e: zb_osif_iteration_process at zb_esp_osif.c.obj:?

4081f0d0: 0x00000000 0x00000000 0x00000000 0x008627a0 0x00000000 0x0006f578 0x7fffffff 0x000000ff
4081f0f0: 0x0000000f 0x00000000 0x40814870 0x420207dc 0x0000000f 0x00000000 0x40814870 0x42020b80
--- 0x420207dc: zb_multimac_mac_logic_iteration_proxy at ??:?
0x42020b80: zb_sched_loop_iteration at ??:?

4081f110: 0x00000000 0x00000000 0x4081f664 0xffffffff 0x00000000 0x40824ea8 0x40824f04 0x00000000
4081f130: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x40824ea8 0x40824f04 0x40824fa8
4081f150: 0x4082504c 0x408250f0 0x40825180 0x420129c6 0x00000000 0x00000000 0x40825180 0x420129dc
--- 0x420129c6: esp_zb_stack_main_loop_iteration at ??:?
0x420129dc: esp_zb_stack_main_loop at ??:?

4081f170: 0x4082504c 0x408250f0 0x40825180 0x42010938 0xa5a5a5a5 0x0001040a 0xa5a50001 0x00000000
--- 0x42010938: esp_zb_task at /Users/arne/oss/zigbee-co2-sensor/main/zigbee_task.c:137

4081f190: 0x00000000 0x459c4000 0x00000000 0xa5a5005f 0xfff60000 0x0000003c 0x40810000 0x32303208
--- 0x40810000: ieee802154_ack_config_pending_bit at /Users/arne/oss/esp/v5.3.2/esp-idf/components/ieee802154/driver/esp_ieee802154_ack.c:159

4081f1b0: 0x30303134 0x00000034 0x324f430a 0x6e655320 0x00726f73 0x6f6c4608 0x6e616972 0x0000004c
4081f1d0: 0x00000002 0x00000002 0x00000002 0x00000408 0x00000002 0x00000000 0x00000006 0x0002bf20
4081f1f0: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x4080bfd4
--- 0x4080bfd4: vPortTaskWrapper at /Users/arne/oss/esp/v5.3.2/esp-idf/components/freertos/FreeRTOS-Kernel/portable/riscv/port.c:258

4081f210: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
4081f230: 0x00000000 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0x00000150
4081f250: 0x4081efa0 0x0000221f 0x4081cc58 0x40813ee8 0x4081f250 0x40813ee0 0x00000014 0x40825774
4081f270: 0x40825774 0x4081f250 0x00000000 0x00000005 0x4081e24c 0x6267695a 0x6d5f6565 0x006e6961
4081f290: 0x00000000 0x4081f240 0x00000005 0x00000001 0x00000000 0x00000000 0x00000000 0x40818eac
4081f2b0: 0x40818f14 0x40818f7c 0x00000000 0x00000000 0x00000001 0x00000000 0x00000000 0x00000000
4081f2d0: 0x42008f0c 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
--- 0x42008f0c: esp_cleanup_r at /Users/arne/oss/esp/v5.3.2/esp-idf/components/newlib/newlib_init.c:43

4081f2f0: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
4081f310: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000
4081f330: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000



ELF file SHA256: a049482e0

Rebooting...

```

**Comment by lorki97** [comment]
@florianL21 informed me about this, since I had the same issue before. There are some changes needed in the sdkconfig file. I'll take a look at my config file in the next couple days and share it with you @schwabe

**Comment by florianL21** [comment]
@schwabe seems like I misremembered a little @lorki97 also had issues that were fixed seemingly without an sdkconfig change. He checked in his fixes here: https://github.com/florianL21/zigbee-co2-sensor/tree/fix%2Fcrashes

Could I maybe ask you to test with this branch since I cannot reproduce the original crash on my side for some reason. If it fixes it for you I would just merge this to main and create another release :)

**Comment by schwabe** [comment]
Unfortunately switching to that branch doesn't make a difference. It still crashes in exactly the same place. 

```
[...]
I (31308) gpio: GPIO[22]| InputEn: 1| OutputEn: 1| OpenDrain: 1| Pullup: 1| Pulldown: 0| Intr:0 
I (31317) gpio: GPIO[23]| InputEn: 1| OutputEn: 1| OpenDrain: 1| Pullup: 1| Pulldown: 0| Intr:0 
I (31327) sdc41_task: First boot after power cycle. Resetting SCD4x sensor state, some i2c errors are expected
I (31880) sdc41_task: serial: 0x5341bb073b5e
I (31880) sdc41_task: Triggering SCD4x single shot measurement... will crash now...
I (36886) sdc41_task: Hum: 62.4 %; Tmp: 16.2 °C; CO2: 1832 ppm

```

(I edited the last message to be sure that I am really running that version)

**Comment by florianL21** [comment]
@schwabe I took some time today and rewrote the whole thing using the arduino framework as I just could not get the ESP-IDF FW to work properly anymore with new builds, not even on my side. If you would like to give it a try you can find it in the switch-to-arduino-framework branch. 
Alternatively if you don't want to install platformio (which this is now using) you can also grab a release binary from here:
https://github.com/florianL21/zigbee-co2-sensor/actions/runs/13294769479/artifacts/2581582883
And flash the bin file with esptool like this:

> esptool.py --chip esp32c6 --port "/dev/ttyACM1" --baud 460800 --before default_reset --after hard_reset write_flash -z --flash_mode dio --flash_freq 80m --flash_size detect 0x0000  co2_sensor_mains_power.bin

**Comment by lorki97** [comment]
Tested it with the pre-built binary, resulting in an issue with the Zigbee cluster.

`(271) ESP_ZIGBEE_CLUSTER: The requested add cluster ID:0x3 is already existed`

<details>
<summary>Full Crash Log</summary>

```
ELF file SHA256: 1947cebe5<\r><\n>
<\r><\n>
Rebooting...<\r><\n>
ESP-ROM:esp32c6-20220919<\r><\n>
Build:Sep 19 2022<\r><\n>
rst:0xc (SW_CPU),boot:0x1e (SPI_FA<3>Te<\0><2><\b><\0>X€<\0><\0><\0><\0><\0><1><\0><\0>àÂ•+k<\n>mode:DIO, clock div:2<\r><\n>
load:0x40875720,len:0x1228<\r><\n>
load:0x4086c110,len:0xd9c<\r><\n>
load:0x4086e610,len:0x2f74<\r><\n>
entry 0x4086c110<\r><\n>
<27>[0;31mE (271) ESP_ZIGBEE_CLUSTER: The requested add cluster ID:0x3 is already existed<27>[0m<\r><\n>
E (321) esp_core_dump_flash: No core dump partition found!<\r><\n>
E (321) esp_core_dump_flash: No core dump partition found!<\r><\n>
<\r><\n>
abort() was called at PC 0x4201350f on core 0<\r><\n>
Core  0 register dump:<\r><\n>
MEPC    : 0x40801be4  RA      : 0x40807824  SP      : 0x40825900  GP      : 0x4080eb94  <\r><\n>
TP      : 0x40825ac0  T0      : 0x37363534  T1      : 0x7271706f  T2      : 0x33323130  <\r><\n>
S0/FP   : 0x4082592c  S1      : 0x4082592c  A0      : 0x40825938  A1      : 0x4082591a  <\r><\n>
A2      : 0x00000000  A3      : 0x40825965  A4      : 0x00000001  A5      : 0x40815000  <\r><\n>
A6      : 0x00000000  A7      : 0x76757473  S2      : 0x00000001  S3      : 0x40810000  <\r><\n>
S4      : 0x42070124  S5      : 0x40823338  S6      : 0x50000000  S7      : 0x4207f000  <\r><\n>
S8      : 0xc1200000  S9      : 0x42be0000  S10     : 0x42700000  S11     : 0x00a299a4  <\r><\n>
T3      : 0x6e6d6c6b  T4      : 0x6a696867  T5      : 0x66656463  T6      : 0x62613938  <\r><\n>
MSTATUS : 0x00001881  MTVEC   : 0x40800001  MCAUSE  : 0x00000007  MTVAL   : 0x00000000  <\r><\n>
MHARTID : 0x00000000  <\r><\n>
<\r><\n>
Stack memory:<\r><\n>
40825900: 0x42700000 0x42be0000 0x40825918 0x4080d252 0x50000000 0x40823338 0x42070030 0x4081006c<\r><\n>
40825920: 0x4082592c 0x40810088 0x40825918 0x31303234 0x66303533 0x42be0000 0x726f6261 0x20292874<\r><\n>
40825940: 0x20736177 0x6c6c6163 0x61206465 0x43502074 0x34783020 0x33313032 0x20663035 0x63206e6f<\r><\n>
40825960: 0x2065726f 0x00000030 0x00000000 0x1f9185ce 0x0000002f 0x408259f4 0x42073d0c 0x42013512<\r><\n>
40825980: 0x50000000 0x00a2b163 0x00000001 0x00000154 0x408089e2 0x408259f4 0x408235fc 0x42009eb6<\r><\n>
408259a0: 0x40825ac0 0x00000046 0x42070124 0x40810000 0x40810000 0x00000000 0x4082317c 0x408084dc<\r><\n>
408259c0: 0x40815000 0x40815000 0xc1200000 0x4207f000 0x50000000 0x00a2b163 0x42070124 0x40810000<\r><\n>
408259e0: 0x40810000 0x42070000 0x40815000 0x42002cfe 0xc1200000 0x42be0000 0x42700000 0x00a20aa4<\r><\n>
40825a00: 0x00000000 0x0004040d 0x0000ffff 0x1f9185ce 0x40810000 0x42070000 0x42070000 0x4200052c<\r><\n>
40825a20: 0x00000000 0x403723d7 0x0000086c 0x4080eb94 0x40825ac0 0x00000000 0x41b91eb8 0x00000000<\r><\n>
40825a40: 0x00000000 0x086c0100 0x00005a64 0x0000c215 0x00000000 0x00000000 0x00000000 0x00000000<\r><\n>
40825a60: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000<\r><\n>
40825a80: 0x00000000 0x00000000 0x00000000 0x408087da 0x00000000 0x00000000 0x00000000 0x00000000<\r><\n>
40825aa0: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5<\r><\n>
40825ac0: 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xa5a5a5a5 0xbaad5678 0x00000068 0xabba1234 0x0000005c<\r><\n>
40825ae0: 0x40825ae0 0x40825ae0 0x40825ae0 0x40825ae0 0x00000000 0x40825af8 0xffffffff 0x40825af8<\r><\n>
40825b00: 0x40825af8 0x00000000 0x40825b0c 0xffffffff 0x40825b0c 0x40825b0c 0x00000001 0x00000001<\r><\n>
40825b20: 0x00000000 0x4001ffff 0x00000000 0xa41f0f87 0xbda4ea03 0x68a0df7b 0x84a13572 0xbaad5678<\r><\n>
40825b40: 0x00000068 0xabba1234 0x0000005c 0x40816c94 0x40816c94 0x40816c98 0x40816c94 0x00000000<\r><\n>
40825b60: 0x40825b64 0xffffffff 0x40825b64 0x40825b64 0x00000000 0x40825b78 0xffffffff 0x40825b78<\r><\n>
40825b80: 0x40825b78 0x00000000 0x00000001 0x00000004 0x7701ffff 0x00000000 0xcc4db062 0x80c9e900<\r><\n>
40825ba0: 0xdecd997e 0x1463245f 0xbaad5678 0x00000010 0xabba1234 0x00000004 0x40825bcc 0xbaad5678<\r><\n>
40825bc0: 0x0000002c 0xabba1234 0x00000020 0x40816e88 0x00000062 0x000186a0 0x000007d0 0x00000000<\r><\n>
40825be0: 0x00000000 0x00000000 0x00000000 0xbaad5678 0x00000014 0xabba1234 0x00000008 0x40825bcc<\r><\n>
40825c00: 0x00000000 0xbaad5678 0x0000001c 0xabba1234 0x00000010 0x40825cf4 0x00000000 0x00000000<\r><\n>
40825c20: 0x40825c34 0xbaad5678 0x00000090 0xabba1234 0x00000084 0x00000000 0x40825cc8 0x00000000<\r><\n>
40825c40: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000<\r><\n>
40825c60: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000<\r><\n>
40825c80: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000<\r><\n>
40825ca0: 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0x00000000 0xbaad5678 0x00000028<\r><\n>
40825cc0: 0xabba1234 0x0000001c 0x00000000 0x00000001 0x00000002 0x00000000 0x00000001 0x0000021b<\r><\n>
40825ce0: 0x00000000 0xbaad5678 0x00000024 0xabba1234 0x00000018 0x36353132 0x00000030 0x00000001<\r><\n>
<\r><\n>
```

</details>
